name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: azureuser
          key: ${{ secrets.SERVER_SSH_KEY }}
          request_pty: true
          script: |
            whoami
            hostname
            sudo -n true
            echo $?
            cd /var/www/html
            sudo git reset --hard
            sudo git pull origin main
            docker restart portfolio-container
            docker restart caddy-proxy
