name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: azureuser
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "USER:"
            whoami

            echo "HOST:"
            hostname

            echo "TEST SUDO:"
            sudo -n true
            echo $?

            echo "DEPLOY:"
            cd /var/www/html
            sudo -n git pull origin main
            sudo -n systemctl reload apache2
